blank_issues_enabled: false
contact_links:
  - name: 💬 Folo's Discord Server
    url: https://discord.gg/AwWcAQ7euc
    about: Questions, ideas, or anything that isn't a bug report or feature request? Chat with us and the community here.
